services:
  # BUILDING LARAVEL IMAGES WITH DOCKER FILE
  web_app_v1:
    build: .
    container_name: "web_app_v1"
    image: "laravel:latest"
    depends_on:
      - mysql
    ports:
      - "9000:80"
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      ASSET_VERSION: 1.2.0
    volumes:
      - 'laravel_shared_storage:/var/www/html/storage'
      - 'laravel_shared_public:/var/www/html/public'

  # PULLING MYSQL IMAGE AND SETTING UP ENVIRONMENT
  mysql:
    image: "mysql:8.0.40"
    container_name: "mysql"
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db_laravel_demo"
      MYSQL_USER: "newuser"
      MYSQL_PASSWORD: "root"
    volumes:
      - 'mysql:/var/lib/mysql'

# VOLUMES THAT WILL BE USED FOR PERSISTENT DATA STORAGE
volumes:
  mysql:
  laravel_shared_storage:
  laravel_shared_public:
